"""Per-population SDE threshold calibration.

A fixed SDE threshold does not encode a fixed false-alarm probability: noise
crosses any given SDE far more often on short-baseline, red-noisy FFI curves
than on quiet two-minute data, so one number over- and under-rejects at the
same time. This module looks up an SDE threshold calibrated against empirical
null distributions (scrambled/bootstrapped no-signal curves searched with the
same machinery as real data) for the light curve's population bin.

The published floor (`paper_tls_sde_min`, Hippke & Heller-style SDE >= 7)
always applies: calibration may only RAISE the bar. Missing tables or bins
fall back to the floor with explicit provenance — never an exception at
runtime, never a silently different gate.

The table is generated by `scripts/calibrate_sde_thresholds.py` and committed
alongside this module; its metadata records the null counts, seeds, and the
search grid the thresholds are valid for.
"""

from __future__ import annotations

import hashlib
import tomllib
from functools import lru_cache
from pathlib import Path
from typing import Any

TABLE_PATH = Path(__file__).with_name("sde_calibration.toml")

# Bucket edges. Cadence mirrors the Nigraha in-domain split (2-min SPOC vs
# FFI-derived products); beta separates white-noise-like curves from ones
# where the Pont et al. 2006 beta says correlated noise is present.
CADENCE_SHORT_MAX_SECONDS = 300.0
BASELINE_SHORT_MAX_DAYS = {"TESS": 35.0, "KEPLER": 90.0}
BETA_QUIET_MAX = 1.3


@lru_cache(maxsize=4)
def _load_table(path_str: str) -> dict[str, Any] | None:
    path = Path(path_str)
    try:
        return tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError, ValueError):
        return None


def table_version(path: Path = TABLE_PATH) -> str | None:
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()[:16]
    except OSError:
        return None


def classify_population(
    *,
    mission: str,
    cadence_seconds: float | None,
    baseline_days: float | None,
    red_noise_beta: float | None,
) -> str:
    mission_key = str(mission or "").strip().lower() or "unknown"
    if cadence_seconds is None or not cadence_seconds > 0:
        cadence_key = "unknown_cadence"
    elif cadence_seconds <= CADENCE_SHORT_MAX_SECONDS:
        cadence_key = "short_cadence"
    else:
        cadence_key = "long_cadence"
    baseline_max = BASELINE_SHORT_MAX_DAYS.get(str(mission or "").upper(), 35.0)
    if baseline_days is None or not baseline_days > 0:
        baseline_key = "unknown_baseline"
    elif baseline_days <= baseline_max:
        baseline_key = "short_baseline"
    else:
        baseline_key = "long_baseline"
    if red_noise_beta is None or not red_noise_beta > 0:
        beta_key = "unknown_beta"
    elif red_noise_beta <= BETA_QUIET_MAX:
        beta_key = "quiet"
    else:
        beta_key = "red"
    return f"{mission_key}_{cadence_key}_{baseline_key}_{beta_key}"


def calibrated_sde_threshold(
    *,
    mission: str,
    cadence_seconds: float | None,
    baseline_days: float | None,
    red_noise_beta: float | None,
    config,
    table_path: Path = TABLE_PATH,
) -> dict[str, Any]:
    """Return the SDE threshold for this light curve's population bin.

    Always returns a usable payload; `source` says whether the value came
    from the calibrated table or the uncalibrated floor.
    """
    floor = float(config.paper_tls_sde_min)
    bin_id = classify_population(
        mission=mission,
        cadence_seconds=cadence_seconds,
        baseline_days=baseline_days,
        red_noise_beta=red_noise_beta,
    )
    payload: dict[str, Any] = {
        "threshold": floor,
        "floor": floor,
        "bin": bin_id,
        "table_version": table_version(table_path),
        "source": "uncalibrated_floor",
    }
    table = _load_table(str(table_path))
    if not table:
        return payload
    bin_entry = (table.get("bins") or {}).get(bin_id)
    if not isinstance(bin_entry, dict):
        return payload
    value = bin_entry.get("sde_threshold")
    if not isinstance(value, (int, float)) or not value > 0:
        return payload
    payload["threshold"] = max(float(value), floor)
    payload["source"] = "calibrated"
    payload["n_null"] = bin_entry.get("n_null")
    payload["fap_target"] = (table.get("metadata") or {}).get("fap_target")
    return payload


def clear_table_cache() -> None:
    _load_table.cache_clear()
